import { useState, useEffect } from 'react'

// Replaces QrScanner. Shows the WhatsApp login code (generated by the
// backend's browser session) while it's waiting to be entered on the
// person's phone. Polls the backend every 2 seconds to check whether a
// code is ready, shows a "slow network" warning if it's taking a long
// time, calls onReady() once WhatsApp has logged in (code disappears),
// and calls onFailed() if the automation script gives up entirely.
//
// The code shown here is generated by the automation script's browser
// session — the person reads it from this screen and types it INTO their
// phone's WhatsApp app (Linked Devices → Link a device → Link with phone
// number instead), not the other way around.
//
// onFailed exists separately from onReady because "code never appeared at
// all" (e.g. the phone-number-login click/selectors failed) has no
// code-then-vanished transition to detect — without an explicit failed
// signal from the backend, this component would just poll forever with
// nothing on screen after the 10-minute timeout.
//
// Rendered as a full-screen blurred overlay so the code is the only thing
// in focus while it's active — the rest of the app sits blurred behind
// it until login succeeds/fails and this unmounts.
//
// NOTE: sends the auth token with every poll. Login-code state is
// per-user on the backend, so without the token the server wouldn't know
// whose code to return — this is what makes it safe for two people to
// start a send at the same time without seeing or overwriting each
// other's code.
function LoginCode({ onReady, onFailed }) {
  const [code, setCode] = useState(null)
  const [everSawCode, setEverSawCode] = useState(false)
  const [slowNetwork, setSlowNetwork] = useState(false)
  // Set if the backend's automation script failed to generate a code at
  // all (e.g. a selector didn't match before the page finished loading).
  // Previously this was console/screenshot-only on the backend, so this
  // overlay just stayed blank with no explanation while the script kept
  // waiting in the background — now we surface it directly.
  const [codeError, setCodeError] = useState(null)

  useEffect(() => {
    const interval = setInterval(async () => {
      try {
        const token = localStorage.getItem('authToken')
        const base = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000/api'
        const res = await fetch(`${base}/login-status/`, {
          headers: token ? { Authorization: `Token ${token}` } : {},
        })
        const data = await res.json()

        if (data.login_failed) {
          clearInterval(interval)
          setCode(null)
          onFailed()
          return
        }

        if (data.login_code_error) {
          setCodeError(data.login_code_error)
        }

        if (data.code_ready) {
          setEverSawCode(true)
          setSlowNetwork(!!data.login_slow)
          setCode(data.login_code)
        } else if (everSawCode) {
          // Code existed before, now it's gone — WhatsApp must be logged in
          clearInterval(interval)
          setCode(null)
          onReady()
        }
      } catch (err) {
        console.error('Login status poll error:', err)
      }
    }, 2000)

    return () => clearInterval(interval)
  }, [everSawCode, onReady, onFailed])

  if (!code && !codeError) return null

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 1000,
        background: 'rgba(245, 243, 238, 0.55)',
        backdropFilter: 'blur(6px)',
        WebkitBackdropFilter: 'blur(6px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 'var(--space-lg)',
      }}
    >
      <div className="bs-card" style={{ textAlign: 'center', maxWidth: '420px' }}>
        {code ? (
          <>
            <h2>Enter this code on your phone</h2>
            <p style={{ marginBottom: 'var(--space-md)' }}>
              Open WhatsApp on your phone → Settings → Linked devices → Link a device → Link with phone number instead — then type the code below.
            </p>
            <div
              style={{
                display: 'inline-block',
                fontFamily: 'var(--font-display)',
                fontSize: '28px',
                fontWeight: 500,
                letterSpacing: '4px',
                padding: '16px 28px',
                border: '1px solid var(--border)',
                borderRadius: 'var(--radius-md)',
                background: 'var(--bg-card-muted)',
                color: 'var(--text-primary)',
              }}
            >
              {code}
            </div>

            {slowNetwork && (
              <p style={{ marginTop: 'var(--space-md)', color: 'var(--danger)', fontWeight: 500, fontSize: '13px' }}>
                This is taking a while — check your connection. Still waiting.
              </p>
            )}
          </>
        ) : (
          <>
            <h2>Couldn't generate a login code</h2>
            <p style={{ marginBottom: 'var(--space-md)' }}>
              Something went wrong starting WhatsApp login. We're still waiting in case it recovers, but if this
              persists, try starting the send again.
            </p>
            <p style={{
              fontSize: '12px',
              fontFamily: 'var(--font-display)',
              color: 'var(--danger)',
              background: 'var(--danger-bg)',
              padding: '10px 12px',
              borderRadius: 'var(--radius-sm)',
              textAlign: 'left',
              wordBreak: 'break-word',
            }}>
              {codeError}
            </p>
          </>
        )}
      </div>
    </div>
  )
}

export default LoginCode