import { useState, useEffect } from 'react'

// Replaces QrScanner. Shows the WhatsApp login code (generated by the
// backend's browser session) while it's waiting to be entered on the
// person's phone. Polls the backend every 2 seconds to check whether a
// code is ready, shows a "slow network" warning if it's taking a long
// time, and calls onReady() once WhatsApp has logged in (code disappears).
//
// The code shown here is generated by the automation script's browser
// session — the person reads it from this screen and types it INTO their
// phone's WhatsApp app (Linked Devices → Link a device → Link with phone
// number instead), not the other way around.
//
// Rendered as a full-screen blurred overlay so the code is the only thing
// in focus while it's active — the rest of the app (contact list, send
// button, etc.) sits blurred behind it until login succeeds and this
// unmounts, at which point everything underneath is back to normal and
// progress polling picks up.
//
// NOTE: sends the auth token with every poll. Login-code state is
// per-user on the backend, so without the token the server wouldn't know
// whose code to return — this is what makes it safe for two people to
// start a send at the same time without seeing or overwriting each
// other's code.
function LoginCode({ onReady }) {
  const [code, setCode] = useState(null)
  const [everSawCode, setEverSawCode] = useState(false)
  const [slowNetwork, setSlowNetwork] = useState(false)

  useEffect(() => {
    const interval = setInterval(async () => {
      try {
        const token = localStorage.getItem('authToken')
        const res = await fetch('http://127.0.0.1:8000/api/login-status/', {
          headers: token ? { Authorization: `Token ${token}` } : {},
        })
        const data = await res.json()

        if (data.code_ready) {
          setEverSawCode(true)
          setSlowNetwork(!!data.login_slow)
          setCode(data.login_code)
        } else if (everSawCode) {
          // Code existed before, now it's gone — WhatsApp must be logged in
          clearInterval(interval)
          setCode(null)
          onReady()
        }
      } catch (err) {
        console.error('Login status poll error:', err)
      }
    }, 2000)

    return () => clearInterval(interval)
  }, [everSawCode, onReady])

  if (!code) return null

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 1000,
        background: 'rgba(245, 243, 238, 0.55)',
        backdropFilter: 'blur(6px)',
        WebkitBackdropFilter: 'blur(6px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 'var(--space-lg)',
      }}
    >
      <div className="bs-card" style={{ textAlign: 'center', maxWidth: '420px' }}>
        <h2>Enter this code on your phone</h2>
        <p style={{ marginBottom: 'var(--space-md)' }}>
          Open WhatsApp on your phone → Settings → Linked devices → Link a device → Link with phone number instead — then type the code below.
        </p>
        <div
          style={{
            display: 'inline-block',
            fontFamily: 'var(--font-display)',
            fontSize: '28px',
            fontWeight: 500,
            letterSpacing: '4px',
            padding: '16px 28px',
            border: '1px solid var(--border)',
            borderRadius: 'var(--radius-md)',
            background: 'var(--bg-card-muted)',
            color: 'var(--text-primary)',
          }}
        >
          {code}
        </div>

        {slowNetwork && (
          <p style={{ marginTop: 'var(--space-md)', color: 'var(--danger)', fontWeight: 500, fontSize: '13px' }}>
            This is taking a while — check your connection. Still waiting.
          </p>
        )}
      </div>
    </div>
  )
}

export default LoginCode